### ISSUE TITLE
[Question] Are the ONNX/TRT checkpoints dynamic?

### ISSUE THREAD

**Issue by salahzoubi** [aihacker111/Efficient-Live-Portrait#22]
Hello,

I'm wondering if the ONNX/TRT files that you have are dynamic inputs (i.e. support batching)? Seems like one of the scripts you have have that option, but I'm wondering if the ONNX files themselves are static or dynamic inputs? 

Thanks!

**Comment by aihacker111** [comment]
@salahzoubi  Yes it's , dynamic
