### ISSUE TITLE
Does this work with Comfyui + Windows 11 + Cuda 12.1?

### ISSUE THREAD

**Issue by piovis2023** [aihacker111/Efficient-Live-Portrait#4]
This project looks great. Curious if i  will work with Comfyui + Windows 11 + Cuda 12.1?

**Comment by aihacker111** [comment]
Of course, it'll work all system but you need to make sure the CUDA and Cudnn you install matching with onnxruntime-gpu follow their document

https://onnxruntime.ai/docs/execution-providers/CUDA-ExecutionProvider.html

**Comment by piovis2023** [comment]
Excellent - thank you do. Do you have any example workflows that I could try? Thanks

**Comment by piovis2023** [comment]
Discussing on another conversation. Thank you
